### ISSUE TITLE
 Can you make a port for Spigot? 

### ISSUE THREAD

**Issue by KenTread** [laymanuel/GravityControl#5]
Your plugin is one of a kind and is the only thing that seems to know how to re-enable this feature in the game. I know this may be a pet project, and you use paper. So I don't expect anything, but  I think the spigot community would love to have gravity control as well. I know my friends, and I would enjoy it, and it would help our building.

**Comment by e-im** [comment]
Does spigot disable sand duping? I am certain disabling sand duping is [something](https://github.com/PaperMC/Paper/blob/master/patches/server/0436-Fix-sand-duping.patch) that [paper](https://github.com/PaperMC/Paper/blob/master/patches/server/0665-Fix-dangerous-end-portal-logic.patch)  does. This plugin on spigot right now would just cause double duplication of sand. The only reason it exists is Paper does not want to add a toggle for sand duplication.

Your issue may be caused by another plugin such as IllegalStack or others disabling sand duping.

**Comment by KenTread** [comment]
> To our knowledge, yes, I know my friend doesn't have the illegal stacks plugin and he owns the computer the server is on. We did some research and while we can't find the patch note we have found several users and posts saying the same thing. Sand duping has been removed. examples  https://www.reddit.com/r/technicalminecraft/comments/kqiy2c/sand_duping_1163_spigot/
https://www.spigotmc.org/threads/is-there-any-way-to-get-sand-dupers-with-spigot.390081/

**Comment by e-im** [comment]
Okay. I was not aware of that. I'll look into this and if it is the case add spigot compatibility. I'd recommend switching to paper though nonetheless-- it provides almost nothing but advantages. Although I'm biased in that regard.

**Comment by e-im** [comment]
Sand duping definitely does work on Spigot. I've both looked through the code and verified no mitigation is in place as well as tried it out. It's likely that a plugin you have is interfering. A common issue people face is plugins like Multiverse being configured to spawn sand through the portal in an arbitrary place. You can configure this in its world configuration. Some people will find sand coming out at `0, 0, 0`.

https://user-images.githubusercontent.com/76139600/188282117-f50caa42-f9ef-4790-bed5-3cffefba5701.mp4
